Merge capability statements
Nictiz/Nictiz-R4-Immunization pull request #6
Opened 2022-11-11 09:50 UTC by ogieling

Merged the capability statements of the client and the server

2022-11-11 12:17 UTC, mikdejong approved these changes

2022-11-18 14:54 UTC, ogieling commented
The capabilityStatement status is changed to active and dependencies are updated

2022-11-19 10:14 UTC, niekvangalen commented
@ogieling 
I updated various things, including the folder structure. Let's look over the CapabilityStatement together, as I am not sure it fully aligns with the IG.

2022-11-19 10:21 UTC, niekvangalen requested changes
See previous comment

2022-11-21 15:16 UTC, merged